version: '3.7'

services:
  url-manager:
    image: hon95/url-manager:latest
    # Dev
    build: ..
    command:
      - '--debug'
      - '--log'
      - '--endpoint=:8000'
      - '--metrics-endpoint=:8001'
    user: 1000:1000
    environment:
      - TZ=Europe/Oslo
    volumes:
      - ./routes.json:/app/routes.json:ro
    ports:
      - 127.0.0.1:8000:8000/tcp
      - 127.0.0.1:8001:8001/tcp
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.url-manager-http.entrypoints=http'
      - 'traefik.http.routers.url-manager-http.rule=Host(`localhost`) || Host(`example.net`) || Host(`www.example.net`)'
      - 'traefik.http.routers.url-manager-https.entrypoints=https'
      - 'traefik.http.routers.url-manager-https.rule=Host(`localhost`) || Host(`example.net`) || Host(`www.example.net`)'
      - 'traefik.http.routers.url-manager-https.tls=true'
      - 'traefik.http.services.url-manager.loadbalancer.server.port=8000'
    restart: unless-stopped

  traefik:
    image: traefik:latest
    command:
      # - '--log.level=DEBUG'
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.http.address=:8080'
      - '--entrypoints.https.address=:8443'
    environment:
      - TZ=Europe/Oslo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:8080:8080/tcp
      - 127.0.0.1:8443:8443/tcp
    restart: unless-stopped
