name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Lint
      run: go install golang.org/x/lint/golint@latest && ~/go/bin/golint -set_exit_status ./...
    - name: Build
      run: go build -o url-manager
  publish-bleeding:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Extract version
      run: echo "version=$(echo 0.0.0-SNAPSHOT+$(TZ=Etc/GMT date "+%Y-%m-%dT%H:%M:%SZ"))" >> $GITHUB_ENV
    - name: Write version to file
      run: sed -i "s/const appVersion.*/const appVersion = \"${{ env.version }}\"/g" meta.go
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: hon95/url-manager
        tags: latest
  publish-stable:
    if: github.event_name == 'release' && github.event.action == 'published' && startsWith(github.ref, 'refs/tags/v')
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Extract versions
      run: |
        echo "version=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_ENV
        echo "version_major=$(echo ${{ env.version }} | grep -Po '^\d+')" >> $GITHUB_ENV
        echo "version_minor=$(echo ${{ env.version }} | grep -Po '^\d+\.\d+')" >> $GITHUB_ENV
    - name: Write version to file
      run: sed -i "s/const appVersion.*/const appVersion = \"${{ env.version }}\"/g" meta.go
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: hon95/url-manager
        tags: latest, ${{ env.version_major }}, ${{ env.version_minor }}, ${{ env.version }}
