name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Lint
      run: go install golang.org/x/lint/golint@latest && ~/go/bin/golint -set_exit_status ./...
    - name: Build
      run: go build -o url-manager

  publish-bleeding:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Update version
      run: echo "version=$(echo 0.0.0-SNAPSHOT+$(TZ=Etc/GMT date "+%Y-%m-%dT%H:%M:%SZ"))" | tee -a $GITHUB_ENV
    - name: Add version to metadata file
      run: sed -i "s/const appVersion.*/const appVersion = \"${{env.version}}\"/g" meta.go
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: hon95/url-manager:latest

  publish-stable:
    if: github.event_name == 'release' && github.event.action == 'published' && startsWith(github.ref, 'refs/tags/v')
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Extract version
      run: |
        echo ${GITHUB_REF}
        echo "version=$(echo ${GITHUB_REF#refs/tags/v})" | tee -a $GITHUB_ENV
        # Check if semantic version (tree numbers)
        echo ${{env.version}} | grep -Po '^\d+\.\d+\.\d+'
        # Extract other version representations
        echo "version_major=$(echo ${{env.version}} | grep -Po '^\d+')" | tee -a $GITHUB_ENV
        echo "version_minor=$(echo ${{env.version}} | grep -Po '^\d+\.\d+')" | tee -a $GITHUB_ENV
        echo "version_patch=$(echo ${{env.version}} | grep -Po '^\d+\.\d+\.\d+')" | tee -a $GITHUB_ENV
    - name: Add version to metadata file
      run: sed -i "s/const appVersion.*/const appVersion = \"${{env.version}}\"/g" meta.go
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: hon95/url-manager:latest, hon95/url-manager:${{env.version_major}}, hon95/url-manager:${{env.version_minor}}, hon95/url-manager:${{env.version_patch}}
